#!/usr/bin/env python3
"""Offline tests for wrap_evidence.py + wrap_verdict.py + wrap_status.sh. No network: the judge is
a fake command. Run: python3 wrap/test/test-wrap.py"""
import glob
import importlib.util
import json
import os
import shutil
import stat
import subprocess
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
BIN = os.path.join(HERE, "..", "bin")
STATUS = os.path.join(BIN, "wrap_status.sh")
# the real shadow ledger; no test may append to it (checked last, see load_tests)
REAL_SHADOW = os.path.expanduser("~/.local/state/wrap/verdicts.jsonl")


def shadow_lines():
    try:
        with open(REAL_SHADOW, "rb") as f:
            return sum(1 for _ in f)
    except FileNotFoundError:
        return 0


SHADOW_BEFORE = shadow_lines()


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def clean_env(**extra):
    """os.environ minus anything that could reach a real judge, a real key or real state."""
    drop = ("JUDGE_", "WRAP_", "OPENROUTER", "CLAUDE_CODE_SESSION_ID")
    e = {k: v for k, v in os.environ.items() if not k.startswith(drop)}
    e.update(extra)
    return e


def fake_key():
    """A key-SHAPED string, assembled at runtime so no key-shaped literal sits in the repo."""
    return "sk-" + "ant-" + "api03-" + "A1b2C3d4" * 5


def write_fakes(tmp):
    """Fake judge (modes via FAKE_MODE / STATE) and a fake redactor. Returns their paths."""
    fake = os.path.join(tmp, "fake-judge.py")
    with open(fake, "w") as f:
        f.write(
            "import json,sys,os\n"
            "req=json.load(sys.stdin)\n"
            "open(os.environ['CAPTURE'],'w').write(json.dumps(req))\n"
            "mode=os.environ.get('FAKE_MODE','ok')\n"
            "if mode=='fail': sys.exit(4)\n"
            "if mode=='empty': print(json.dumps({'verdicts':[]})); sys.exit(0)\n"
            "vs=[]\n"
            "for q in req['questions']:\n"
            "  t=q['type']\n"
            "  a=(0.9 if q['id'].startswith('req') else 0.0) if t=='yes_no' else 0 if t=='score' else os.environ.get('STATE','delivered-verified') if q['id'].startswith('state') else list(q['options'])[0]\n"
            "  if mode=='down': vs.append({'id':q['id'],'escalate':True,'reason':'unreachable'}); continue\n"
            "  if q['id']==os.environ.get('DROP_ID'): continue\n"
            "  if q['id']==os.environ.get('MALFORM_ID'): a='banana'\n"
            "  vs.append({'id':q['id'],'type':q['type'],'answer':a,'confidence':0.9,'escalate':False})\n"
            "print(json.dumps({'verdicts':vs,'model':'fake','latencyMs':1,'usage':{}}))\n"
            "if mode=='escalated': sys.exit(3)\n")
    redactor = os.path.join(tmp, "redact.py")
    with open(redactor, "w") as f:
        f.write("import sys; sys.stdout.write(sys.stdin.read().replace('SECRETCLIENT','<client>'))\n")
    return fake, redactor


def load(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(BIN, f"{name}.py"))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


we, wv = load("wrap_evidence"), load("wrap_verdict")


def user(text, sidechain=False, **kw):
    return json.dumps({"type": "user", "isSidechain": sidechain, "sessionId": "S1",
                       "cwd": "/w", "timestamp": "t", "message": {"content": text}, **kw})


def tool_result(text):
    return json.dumps({"type": "user", "isSidechain": False, "cwd": "/w",
                       "message": {"content": [{"type": "tool_result", "content": text}]}})


def assistant(text=None, tools=()):
    content = ([{"type": "text", "text": text}] if text else []) + [
        {"type": "tool_use", "name": n, "input": i} for n, i in tools]
    return json.dumps({"type": "assistant", "isSidechain": False, "cwd": "/w",
                       "message": {"content": content}})


TRANSCRIPT = [
    user("build the thing"),
    user("<command-name>/plan</command-name>\n<command-args>make it fast</command-args>"),
    user("<task-notification>agent done</task-notification>"),
    user("<local-command-stdout>Enabled plan mode</local-command-stdout>"),
    user("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>"),
    user("<command-name>/clear</command-name>\n<command-args></command-args>"),
    user("Base directory for this skill: /home/dana/.claude/skills/wrap\n# Wrap"),
    user("[Request interrupted by user for tool use]"),
    user("subagent chatter", sidechain=True),
    json.dumps({"type": "attachment", "isSidechain": False,
                "attachment": {"type": "queued_command", "prompt": "also add tests"}}),
    json.dumps({"type": "attachment", "isSidechain": False,
                "attachment": {"type": "queued_command", "prompt": "also add tests"}}),
    tool_result("The user doesn't want to proceed... the user said:\ntighten it"),
    tool_result("Your questions have been answered: \"Tier?\"=\"Redacted\""),
    tool_result("ordinary tool output"),
    assistant("working", tools=[("Edit", {"file_path": "/repo/a/x.py"}),
                                ("Read", {"file_path": "/repo/read-only/y.py"}),
                                ("Bash", {"command": "git -C /repo/b commit -m x"}),
                                ("Bash", {"command": "cd /repo/c && git push -u origin f"}),
                                ("Bash", {"command": "git -C /repo/d log --oneline"}),
                                ("Bash", {"command": "gh pr create --draft"})]),
    user("ship it<system-reminder>noise</system-reminder>"),
    assistant("DONE — shipped and tested"),
]


class Evidence(unittest.TestCase):
    def setUp(self):
        self.sid, self.asks, self.report, self.paths = we.parse(TRANSCRIPT)

    def test_session_and_report(self):
        self.assertEqual(self.sid, "S1")
        self.assertEqual(self.report, "DONE — shipped and tested")

    def test_all_four_channels_noise_excluded(self):
        got = [(a["channel"], a["text"]) for a in self.asks]
        self.assertEqual(got, [
            ("prompt", "build the thing"),
            ("prompt", "/plan make it fast"),
            ("queued", "also add tests"),          # de-duplicated
            ("feedback", "tighten it"),
            ("decision", '"Tier?"="Redacted"'),
            ("prompt", "ship it"),                 # system-reminder stripped
        ])
        self.assertEqual([a["i"] for a in self.asks], [1, 2, 3, 4, 5, 6])

    def test_write_paths_only(self):
        self.assertIn("/repo/a/x.py", self.paths)
        self.assertIn("/repo/b", self.paths)
        self.assertIn("/repo/c", self.paths)
        self.assertIn("/w", self.paths)            # bare gh pr create -> cwd
        self.assertNotIn("/repo/read-only/y.py", self.paths)
        self.assertNotIn("/repo/d", self.paths)    # git log is a read

    def test_build_no_git(self):
        ev = we.build(TRANSCRIPT, use_git=False)
        self.assertEqual(ev["repos"], [])
        self.assertEqual(len(ev["asks"]), 6)


class BranchState(unittest.TestCase):
    def f(self, **kw):
        base = {"branch": "feat/x", "default": "origin/main", "upstream": "origin/feat/x",
                "vs_default": {"ahead": 2, "behind": 0}, "vs_upstream": {"ahead": 0, "behind": 0},
                "pr": None}
        base.update(kw)
        return we.branch_state(base)

    def test_states(self):
        self.assertEqual(self.f(), "pushed")
        self.assertEqual(self.f(vs_upstream={"ahead": 1, "behind": 0}), "unpushed")
        self.assertEqual(self.f(upstream=None), "unpushed")
        self.assertEqual(self.f(vs_default={"ahead": 0, "behind": 0}), "nothing-ahead")
        self.assertEqual(self.f(pr={"state": "MERGED"}), "merged")
        self.assertEqual(self.f(branch="main"), "on-default")


class Claimed(unittest.TestCase):
    def test_parse(self):
        self.assertEqual(wv.claimed_status("DONE: all green"), "DONE")
        self.assertEqual(wv.claimed_status("\n**PARTIAL** — X remains"), "PARTIAL")
        self.assertEqual(wv.claimed_status("Done. Shipped."), "DONE")
        self.assertEqual(wv.claimed_status("Still going — two left"), "PARTIAL")
        self.assertEqual(wv.claimed_status("I built a thing"), "none")
        self.assertEqual(wv.claimed_status(None), "none")


def V(answer, escalate=False, conf=0.9):
    return {"answer": answer, "escalate": escalate, "confidence": conf}


ASKS = [{"i": 1, "channel": "prompt", "text": "build A"},
        {"i": 2, "channel": "prompt", "text": "build B"},
        {"i": 3, "channel": "decision", "text": "tier=x"}]


def verdicts(s1="delivered-verified", s2="delivered-verified", sup2=0.0, unver=0.0, lands=0.0,
             req2=0.9, esc1=False):
    return {"req_1": V(0.9), "sup_1": V(0.0), "state_1": V(s1, escalate=esc1),
            "req_2": V(req2), "sup_2": V(sup2), "state_2": V(s2),
            "unverified_claim": V(unver), "lands_on_user": V(lands)}


class Combine(unittest.TestCase):
    def test_all_verified_done(self):
        r = wv.combine(ASKS, verdicts(), "DONE")
        self.assertEqual((r["computed"], r["consistent"]), ("DONE", True))

    def test_decision_asks_never_judged(self):
        self.assertNotIn("req_3", {q["id"] for q in wv.questions(ASKS)})
        self.assertEqual([a["n"] for a in wv.combine(ASKS, verdicts(), "DONE")["asks"]], [1, 2])

    def test_one_partial_downgrades_done_claim(self):
        r = wv.combine(ASKS, verdicts(s2="partial"), "DONE")
        self.assertEqual((r["computed"], r["consistent"]), ("PARTIAL", False))
        self.assertIn("#2 partial", r["reasons"])

    def test_superseded_ask_ignored(self):
        r = wv.combine(ASKS, verdicts(s2="not-started", sup2=0.9), "DONE")
        self.assertEqual(r["computed"], "DONE")

    def test_non_request_ignored(self):
        r = wv.combine(ASKS, verdicts(s2="not-started", req2=0.1), "DONE")
        self.assertEqual(r["computed"], "DONE")

    def test_unverified_claim_blocks_done(self):
        r = wv.combine(ASKS, verdicts(unver=0.8), "DONE")
        self.assertEqual(r["computed"], "PARTIAL")

    def test_lands_on_user_is_blocked(self):
        r = wv.combine(ASKS, verdicts(lands=0.9), "DONE")
        self.assertEqual((r["computed"], r["consistent"]), ("BLOCKED", False))
        r = wv.combine(ASKS, verdicts(lands=0.9), "BLOCKED")
        self.assertTrue(r["consistent"])

    def test_escalated_state_never_done_never_downgrades(self):
        # unsure is surfaced for a human, not treated as a gap
        r = wv.combine(ASKS, verdicts(esc1=True), "DONE")
        self.assertEqual((r["computed"], r["consistent"]), ("UNCLEAR", True))
        self.assertIn("#1", r["unsure"])
        self.assertFalse(r["asks"][0]["sure"])

    def test_escalated_gap_state_does_not_fire(self):
        v = verdicts(s1="not-started", esc1=True)
        self.assertEqual(wv.combine(ASKS, v, "DONE")["computed"], "UNCLEAR")

    def test_confident_unverified_delivery_is_a_gap(self):
        r = wv.combine(ASKS, verdicts(s2="delivered-unverified"), "DONE")
        self.assertEqual(r["computed"], "PARTIAL")

    def test_escalated_flags_listed_not_applied(self):
        v = verdicts() | {"unverified_claim": V(0.9, escalate=True),
                          "lands_on_user": V(0.9, escalate=True)}
        r = wv.combine(ASKS, v, "DONE")
        self.assertEqual(r["computed"], "DONE")
        self.assertEqual(set(r["unsure"]), {"unverified_claim", "lands_on_user"})

    def test_judge_reads_claim_when_no_status_word(self):
        v = verdicts(s2="partial") | {"claimed_j": V("DONE")}
        r = wv.combine(ASKS, v, "none")
        self.assertEqual((r["claimed"], r["claimed_source"], r["consistent"]),
                         ("DONE", "judge-read", False))
        # an escalated read does not count
        v["claimed_j"] = V("DONE", escalate=True)
        self.assertEqual(wv.combine(ASKS, v, "none")["claimed"], "none")

    def test_completeness_recorded(self):
        r = wv.combine(ASKS, verdicts() | {"completeness": V(3.4)}, "DONE")
        self.assertEqual(r["completeness"], 3.4)

    def test_question_battery_shape(self):
        ids = [q["id"] for q in wv.questions(ASKS)]
        self.assertEqual(ids[-4:], ["unverified_claim", "lands_on_user", "claimed_j", "completeness"])
        score = [q for q in wv.questions(ASKS) if q["id"] == "completeness"][0]
        self.assertEqual(len(score["levels"]), 5)

    def test_verdict_shape_check(self):
        qs = wv.questions(ASKS)
        answer = {"yes_no": lambda q: 0.2, "choice": lambda q: list(q["options"])[0],
                  "score": lambda q: 2.5}
        good = {q["id"]: V(answer[q["type"]](q)) for q in qs}
        ok = lambda vs: wv.bad_verdicts(qs, {"verdicts": list(vs)})
        self.assertEqual(ok(dict(v, id=k) for k, v in good.items()), ([], []))
        # an escalated verdict that never reached the judge carries answer null: well-formed
        esc = [dict(v, id=k) for k, v in good.items()]
        esc[0] = {"id": esc[0]["id"], "answer": None, "escalate": True, "confidence": 0}
        self.assertEqual(ok(esc), ([], []))
        bad = [dict(v, id=k) for k, v in good.items()]
        bad[0]["answer"] = None                          # not escalated, no answer
        bad[1]["answer"] = 1.5                           # P(yes) outside [0, 1]
        bad[2] = "not a verdict"                         # state_1's slot, not a dict
        self.assertEqual(ok(bad), (["state_1"], ["req_1", "sup_1"]))
        self.assertEqual(wv.bad_verdicts(qs, {"verdicts": "nope"})[0], [q["id"] for q in qs])
        self.assertEqual(wv.bad_verdicts(qs, ["not", "an", "object"])[0], [q["id"] for q in qs])

    def test_underclaim_is_consistent(self):
        # The judge only downgrades: claiming PARTIAL when computed DONE is fine
        self.assertTrue(wv.combine(ASKS, verdicts(), "PARTIAL")["consistent"])

    def test_missing_status_word_inconsistent(self):
        r = wv.combine(ASKS, verdicts(), "none")
        self.assertFalse(r["consistent"])

    def test_no_active_requests(self):
        r = wv.combine(ASKS, verdicts(req2=0.1) | {"req_1": V(0.1)}, "DONE")
        self.assertEqual((r["computed"], r["consistent"]), ("n/a", True))


class EndToEnd(unittest.TestCase):
    """Runs the CLI with a fake judge and a fake redactor."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.fake, self.redactor = write_fakes(self.tmp)
        self.capture = os.path.join(self.tmp, "req.json")
        self.ev = {"session_id": "S1", "report": "DONE — built A",
                   "asks": [{"i": 1, "channel": "prompt", "text": "build A for SECRETCLIENT"}],
                   "repos": []}

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def run_cli(self, *args, **env):
        e = clean_env(JUDGE_CMD=f"{sys.executable} {self.fake}", JUDGE_REDACT=self.redactor,
                      CAPTURE=self.capture)
        e.update(env)
        return subprocess.run([sys.executable, os.path.join(BIN, "wrap_verdict.py"), "--no-log",
                               *args], input=json.dumps(self.ev), capture_output=True, text=True,
                              env=e)

    def test_consistent_exit0_and_state_redacted(self):
        r = self.run_cli()
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(json.loads(r.stdout)["computed"], "DONE")
        sent = read(self.capture)
        self.assertNotIn("SECRETCLIENT", sent)
        self.assertIn("<client>", sent)

    def test_overclaim_exit1(self):
        r = self.run_cli(STATE="partial")
        self.assertEqual(r.returncode, 1)
        self.assertEqual(json.loads(r.stdout)["computed"], "PARTIAL")

    def test_report_file_overrides(self):
        rp = os.path.join(self.tmp, "report.md")
        with open(rp, "w") as f:
            f.write("PARTIAL — B remains\n")
        r = self.run_cli("--report", rp, STATE="partial")
        self.assertEqual(r.returncode, 0)

    def test_judge_failure_is_advisory_exit3(self):
        r = self.run_cli(FAKE_MODE="fail")
        self.assertEqual(r.returncode, 3)
        self.assertIsNone(json.loads(r.stdout)["computed"])

    def test_judge_exit3_escalated_is_a_result_not_an_error(self):
        r = self.run_cli(FAKE_MODE="escalated")
        self.assertEqual(r.returncode, 0, r.stdout)
        self.assertEqual(json.loads(r.stdout)["computed"], "DONE")

    def test_judge_unreachable_is_advisory_exit3(self):
        self.assertEqual(self.run_cli(FAKE_MODE="down").returncode, 3)

    def test_no_judge_configured_is_advisory_exit3(self):
        e = clean_env(JUDGE_REDACT=self.redactor, CAPTURE=self.capture)
        r = subprocess.run([sys.executable, os.path.join(BIN, "wrap_verdict.py"), "--no-log"],
                           input=json.dumps(self.ev), capture_output=True, text=True, env=e)
        self.assertEqual(r.returncode, 3, r.stderr)
        out = json.loads(r.stdout)
        self.assertIsNone(out["computed"])
        self.assertIn("JUDGE_CMD", out["advisory"])
        self.assertFalse(os.path.exists(self.capture))

    def test_redactor_unset_sends_unredacted_row_says_false(self):
        # redactor is optional: unset sends the state unredacted (key shapes still refused)
        log = os.path.join(self.tmp, "l.jsonl")
        e = clean_env(JUDGE_CMD=f"{sys.executable} {self.fake}", CAPTURE=self.capture)
        r = subprocess.run([sys.executable, os.path.join(BIN, "wrap_verdict.py"), "--log", log],
                           input=json.dumps(self.ev), capture_output=True, text=True, env=e)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("SECRETCLIENT", read(self.capture))
        self.assertIs(json.loads(read(log).strip())["redacted"], False)
        self.assertIs(json.loads(r.stdout)["redacted"], False)

    def test_redactor_path_missing_sends_unredacted(self):
        r = self.run_cli(JUDGE_REDACT=os.path.join(self.tmp, "nonexistent.py"))
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("SECRETCLIENT", read(self.capture))
        self.assertIs(json.loads(r.stdout)["redacted"], False)
        self.assertIn("unredacted", r.stderr)

    def test_redactor_refusal_still_sends_nothing(self):
        # when a redactor IS configured and present, it stays fail-closed
        refuser = os.path.join(self.tmp, "refuse.py")
        with open(refuser, "w") as f:
            f.write("import sys; sys.exit(2)\n")
        r = self.run_cli(JUDGE_REDACT=refuser)
        self.assertEqual(r.returncode, 3)
        self.assertIn("refused", json.loads(r.stdout)["advisory"])
        self.assertFalse(os.path.exists(self.capture))

    def test_key_shaped_state_refused_exit2(self):
        self.ev["asks"][0]["text"] += " key " + fake_key()
        r = self.run_cli()
        self.assertEqual(r.returncode, 2)
        self.assertEqual(r.stdout, "")
        self.assertFalse(os.path.exists(self.capture))
        self.assertNotIn(fake_key(), r.stderr)
        self.assertIn("key-shaped", r.stderr)

    def test_key_removed_by_redactor_is_sent(self):
        # the refusal checks what would be SENT: a redactor that strips the key clears it
        stripper = os.path.join(self.tmp, "strip.py")
        with open(stripper, "w") as f:
            f.write("import re,sys; sys.stdout.write(re.sub(r'sk-ant-[A-Za-z0-9_-]+', "
                    "'<secret>', sys.stdin.read()))\n")
        self.ev["asks"][0]["text"] += " key " + fake_key()
        r = self.run_cli(JUDGE_REDACT=stripper)
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertNotIn(fake_key(), read(self.capture))
        self.assertIs(json.loads(r.stdout)["redacted"], True)

    def test_empty_verdicts_list_is_bad_input_exit2(self):
        # {"verdicts": []} used to reach combine() as "no active request" -> n/a -> DONE passes
        r = self.run_cli(FAKE_MODE="empty")
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertEqual(r.stdout, "")
        self.assertIn("bad-verdicts missing=all(", r.stderr)

    def test_one_verdict_missing_exit2_names_it(self):
        r = self.run_cli(DROP_ID="state_1")
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertEqual(r.stdout, "")
        self.assertIn("bad-verdicts missing=state_1", r.stderr)

    def test_one_malformed_verdict_exit2_names_it(self):
        r = self.run_cli(MALFORM_ID="req_1")          # a noul answered with a string
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertIn("malformed=req_1", r.stderr)
        r = self.run_cli(MALFORM_ID="state_1")        # a choice outside its options
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertIn("malformed=state_1", r.stderr)

    def test_bad_stdin_exit2(self):
        r = subprocess.run([sys.executable, os.path.join(BIN, "wrap_verdict.py")],
                           input="not json", capture_output=True, text=True)
        self.assertEqual(r.returncode, 2)

    def test_log_line_written(self):
        log = os.path.join(self.tmp, "l.jsonl")
        e = clean_env(JUDGE_CMD=f"{sys.executable} {self.fake}", JUDGE_REDACT=self.redactor,
                      CAPTURE=self.capture)
        subprocess.run([sys.executable, os.path.join(BIN, "wrap_verdict.py"), "--log", log],
                       input=json.dumps(self.ev), capture_output=True, text=True, env=e)
        row = json.loads(read(log).strip())
        self.assertEqual((row["site"], row["mode"], row["computed"]), ("wrap:verdict", "shadow", "DONE"))
        self.assertIs(row["redacted"], True)


class Status(unittest.TestCase):
    """wrap_status.sh: transcript -> wrap_evidence | wrap_verdict, plus the side effects it owns.
    HOME, WRAP_STATE_DIR and WRAP_VERDICT_LOG all point into a temp dir."""

    def setUp(self):
        self.tmp = tempfile.mkdtemp()
        self.fake, self.redactor = write_fakes(self.tmp)
        self.capture = os.path.join(self.tmp, "req.json")
        self.home = os.path.join(self.tmp, "home")
        self.state = os.path.join(self.tmp, "state")
        self.vlog = os.path.join(self.tmp, "verdict.jsonl")
        self.transcript = os.path.join(self.tmp, "t.jsonl")
        self.write_transcript(self.transcript)
        self.draft = os.path.join(self.tmp, "draft.md")
        with open(self.draft, "w") as f:
            f.write("DONE — built A\nJudge: pending\n")

    def tearDown(self):
        shutil.rmtree(self.tmp, ignore_errors=True)

    def write_transcript(self, path, sid="S1", ask="build A"):
        line = {"type": "user", "isSidechain": False, "cwd": "/w", "timestamp": "t",
                "message": {"content": ask}}
        if sid:
            line["sessionId"] = sid
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as f:
            f.write(json.dumps(line) + "\n" + assistant("DONE — built A") + "\n")

    def run_status(self, *args, **env):
        e = clean_env(HOME=self.home, JUDGE_CMD=f"{sys.executable} {self.fake}",
                      CAPTURE=self.capture, WRAP_STATE_DIR=self.state, WRAP_VERDICT_LOG=self.vlog)
        e.update(env)
        return subprocess.run([STATUS, *args], capture_output=True, text=True, env=e)

    def verdict_files(self):
        return sorted(glob.glob(os.path.join(self.state, "*.json")))

    def test_exit0_verdict_file_0600_equals_stdout(self):
        r = self.run_status("--transcript", self.transcript, self.draft)
        self.assertEqual(r.returncode, 0, r.stderr)
        p = os.path.join(self.state, "S1.json")
        self.assertEqual(stat.S_IMODE(os.stat(p).st_mode), 0o600)
        self.assertEqual(read(p), r.stdout)
        self.assertEqual(json.loads(r.stdout)["computed"], "DONE")
        self.assertEqual(stat.S_IMODE(os.stat(self.state).st_mode) & 0o077, 0)

    def test_exit1_overclaim_passes_through(self):
        r = self.run_status("--transcript", self.transcript, self.draft, STATE="partial")
        self.assertEqual(r.returncode, 1, r.stderr)
        v = json.loads(read(os.path.join(self.state, "S1.json")))
        self.assertEqual((v["computed"], v["claimed"], v["consistent"]), ("PARTIAL", "DONE", False))

    def test_exit3_advisory_passes_through_and_is_saved(self):
        r = self.run_status("--transcript", self.transcript, self.draft, FAKE_MODE="fail")
        self.assertEqual(r.returncode, 3, r.stderr)
        p = os.path.join(self.state, "S1.json")
        self.assertEqual(read(p), r.stdout)
        self.assertIsNone(json.loads(r.stdout)["computed"])

    def test_exit2_from_verdict_writes_no_file(self):
        # a key-shaped string in the state: wrap_verdict refuses (2), nothing sent or saved
        self.write_transcript(self.transcript, ask="build A " + fake_key())
        r = self.run_status("--transcript", self.transcript, self.draft)
        self.assertEqual(r.returncode, 2)
        self.assertEqual(self.verdict_files(), [])
        self.assertFalse(os.path.exists(self.capture))
        self.assertNotIn(fake_key(), r.stdout + r.stderr)

    def test_crash_is_bad_input_not_overclaim(self):
        # wrap_verdict dying with a traceback exits 1 with no JSON: that is not an overclaim.
        # Run a copy of the wrapper beside a wrap_verdict.py stub that does exactly that.
        stub = os.path.join(self.tmp, "bin")
        os.makedirs(stub)
        for name in ("wrap_status.sh", "wrap_evidence.py"):
            shutil.copy2(os.path.join(BIN, name), stub)
        with open(os.path.join(stub, "wrap_verdict.py"), "w") as f:
            f.write("import sys; sys.stdin.read(); sys.stderr.write('Traceback: boom\\n'); "
                    "sys.exit(1)\n")
        e = clean_env(HOME=self.home, WRAP_STATE_DIR=self.state, WRAP_VERDICT_LOG=self.vlog)
        r = subprocess.run([os.path.join(stub, "wrap_status.sh"), "--transcript", self.transcript,
                            self.draft], capture_output=True, text=True, env=e)
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertIn("not a verdict", r.stderr)
        self.assertEqual(self.verdict_files(), [])

    def test_missing_verdicts_exit2_no_file_log_names_ids(self):
        r = self.run_status("--transcript", self.transcript, self.draft, DROP_ID="state_1")
        self.assertEqual(r.returncode, 2, r.stdout)
        self.assertEqual(self.verdict_files(), [])
        line = read(os.path.join(self.state, "wrap_status.log")).splitlines()[-1]
        self.assertRegex(line, r" exit=2 computed=- claimed=- missing=state_1$")
        self.run_status("--transcript", self.transcript, self.draft, FAKE_MODE="empty")
        line = read(os.path.join(self.state, "wrap_status.log")).splitlines()[-1]
        self.assertRegex(line, r" exit=2 computed=- claimed=- missing=all\(\d+\)$")

    def test_transcript_resolved_from_session_id(self):
        proj = os.path.join(self.home, ".claude", "projects", "-Users-x-wt")
        self.write_transcript(os.path.join(proj, "SID-7.jsonl"))
        r = self.run_status(self.draft, CLAUDE_CODE_SESSION_ID="SID-7")
        self.assertEqual(r.returncode, 0, r.stderr)
        # the file is named from the verdict's session_id (the transcript's), not the env
        self.assertEqual(self.verdict_files(), [os.path.join(self.state, "S1.json")])

    def test_transcript_zero_or_many_matches_exit2(self):
        projects = os.path.join(self.home, ".claude", "projects")
        r = self.run_status(self.draft, CLAUDE_CODE_SESSION_ID="SID-7")
        self.assertEqual(r.returncode, 2)
        self.assertIn("no transcript", r.stderr)
        for d in ("-a", "-b"):
            self.write_transcript(os.path.join(projects, d, "SID-7.jsonl"))
        r = self.run_status(self.draft, CLAUDE_CODE_SESSION_ID="SID-7")
        self.assertEqual(r.returncode, 2)
        self.assertIn("2 transcripts", r.stderr)
        self.assertEqual(self.run_status(self.draft).returncode, 2)          # id unset
        self.assertEqual(self.run_status(self.draft, CLAUDE_CODE_SESSION_ID="../-a/SID-7")
                         .returncode, 2)                                     # not an id
        self.assertEqual(self.verdict_files(), [])
        self.assertFalse(os.path.exists(self.capture))

    def test_session_id_falls_back_to_env(self):
        self.write_transcript(self.transcript, sid=None)
        r = self.run_status("--transcript", self.transcript, self.draft,
                            CLAUDE_CODE_SESSION_ID="ENV-1")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertEqual(self.verdict_files(), [os.path.join(self.state, "ENV-1.json")])

    def test_missing_draft_exit2_no_file(self):
        r = self.run_status("--transcript", self.transcript, os.path.join(self.tmp, "nope.md"))
        self.assertEqual(r.returncode, 2)
        self.assertEqual(self.verdict_files(), [])
        self.assertEqual(self.run_status().returncode, 2)                    # no draft at all

    def test_one_log_line_per_run_rc_before_timestamp(self):
        self.run_status("--transcript", self.transcript, self.draft, STATE="partial")
        self.run_status("--transcript", self.transcript, os.path.join(self.tmp, "nope.md"))
        log = os.path.join(self.state, "wrap_status.log")
        lines = read(log).splitlines()
        self.assertEqual(len(lines), 2)
        self.assertRegex(lines[0], r"^\[\d{4}-\d\d-\d\dT\d\d:\d\d:\d\dZ\] argv=\[--transcript .+\] "
                                   r"exit=1 computed=PARTIAL claimed=DONE$")
        self.assertRegex(lines[1], r"\] argv=\[.+\] exit=2 computed=- claimed=-$")
        self.assertEqual(stat.S_IMODE(os.stat(log).st_mode), 0o600)

    def test_verdict_log_goes_where_told(self):
        r = self.run_status("--transcript", self.transcript, self.draft)
        self.assertEqual(r.returncode, 0, r.stderr)
        row = json.loads(read(self.vlog).strip())
        self.assertEqual((row["session"], row["mode"], row["redacted"]), ("S1", "shadow", False))
        self.assertFalse(os.path.exists(
            os.path.join(self.home, ".local", "state", "wrap", "verdicts.jsonl")))


class ShadowLogUntouched(unittest.TestCase):
    def test_real_shadow_log_unchanged_by_suite(self):
        self.assertEqual(shadow_lines(), SHADOW_BEFORE)


def load_tests(loader, standard, pattern):
    """Run ShadowLogUntouched last, after every test that could have written the log."""
    rest = [s for s in standard if not any(isinstance(t, ShadowLogUntouched) for t in s)]
    return unittest.TestSuite(rest + [loader.loadTestsFromTestCase(ShadowLogUntouched)])


if __name__ == "__main__":
    unittest.main(verbosity=1)
